#############################################################################
# Makefile for building: cuNICS
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  cuNICS.pro
# Template: app
# Command: /usr/lib/i386-linux-gnu/qt5/bin/qmake -o Makefile cuNICS.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtGui -isystem /usr/include/i386-linux-gnu/qt5/QtSql -isystem /usr/include/i386-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/i386-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = cuNICS1.0.0
DISTDIR = /home/admin/Documents/COMP-3004-Project/.tmp/cuNICS1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Sql -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		database/DatabaseControl.cpp \
		memory/Address.cpp \
		memory/ContinuingRole.cpp \
		memory/Date.cpp \
		memory/Deduction.cpp \
		memory/Employee.cpp \
		memory/EmployeeRole.cpp \
		memory/EntityControl.cpp \
		memory/LeavePeriod.cpp \
		memory/Raise.cpp \
		memory/TermRole.cpp \
		memory/User.cpp \
		integration/Transaction.cpp \
		integration/TransactionFileCreator.cpp \
		integration/AttributePair.cpp \
		integration/TransactionFileHandler.cpp \
		integration/AddEmployeeTransaction.cpp \
		integration/UpdateBasicTransaction.cpp \
		integration/UpdatePayTransaction.cpp \
		integration/ApplyRaiseTransaction.cpp \
		integration/AddLeaveTransaction.cpp \
		memory/EntityManager.cpp \
		database/StorageManager.cpp \
		integration/TransactionIntegrator.cpp \
		database/StorageConnection.cpp \
		integration/AddRoleTransaction.cpp \
		gui/mainwindow.cpp \
		gui/secondwindow.cpp \
		gui/thirdwindow.cpp \
		gui/fourthwindow.cpp \
		gui/dataintegration.cpp \
		ApplicationLogic.cpp \
		memory/PayrollSummary.cpp moc_mainwindow.cpp \
		moc_secondwindow.cpp \
		moc_thirdwindow.cpp \
		moc_fourthwindow.cpp \
		moc_dataintegration.cpp
OBJECTS       = main.o \
		DatabaseControl.o \
		Address.o \
		ContinuingRole.o \
		Date.o \
		Deduction.o \
		Employee.o \
		EmployeeRole.o \
		EntityControl.o \
		LeavePeriod.o \
		Raise.o \
		TermRole.o \
		User.o \
		Transaction.o \
		TransactionFileCreator.o \
		AttributePair.o \
		TransactionFileHandler.o \
		AddEmployeeTransaction.o \
		UpdateBasicTransaction.o \
		UpdatePayTransaction.o \
		ApplyRaiseTransaction.o \
		AddLeaveTransaction.o \
		EntityManager.o \
		StorageManager.o \
		TransactionIntegrator.o \
		StorageConnection.o \
		AddRoleTransaction.o \
		mainwindow.o \
		secondwindow.o \
		thirdwindow.o \
		fourthwindow.o \
		dataintegration.o \
		ApplicationLogic.o \
		PayrollSummary.o \
		moc_mainwindow.o \
		moc_secondwindow.o \
		moc_thirdwindow.o \
		moc_fourthwindow.o \
		moc_dataintegration.o
DIST          = cuNICSdb.sql \
		cuNICS.db \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf \
		cuNICS.pro database/DatabaseControl.h \
		memory/Address.h \
		memory/ContinuingRole.h \
		memory/Date.h \
		memory/Deduction.h \
		memory/Employee.h \
		memory/EmployeeRole.h \
		memory/EntityControl.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		memory/TermRole.h \
		memory/User.h \
		integration/Transaction.h \
		integration/TransactionFileCreator.h \
		integration/AttributePair.h \
		integration/IntegrationUtils.h \
		integration/TransactionFileHandler.h \
		integration/AddEmployeeTransaction.h \
		integration/UpdateBasicTransaction.h \
		integration/UpdatePayTransaction.h \
		integration/ApplyRaiseTransaction.h \
		integration/AddLeaveTransaction.h \
		memory/EntityManager.h \
		database/StorageManager.h \
		integration/TransactionIntegrator.h \
		database/StorageConnection.h \
		integration/AddRoleTransaction.h \
		gui/mainwindow.h \
		gui/secondwindow.h \
		gui/thirdwindow.h \
		gui/fourthwindow.h \
		gui/dataintegration.h \
		ApplicationLogic.h \
		memory/PayrollSummary.h main.cpp \
		database/DatabaseControl.cpp \
		memory/Address.cpp \
		memory/ContinuingRole.cpp \
		memory/Date.cpp \
		memory/Deduction.cpp \
		memory/Employee.cpp \
		memory/EmployeeRole.cpp \
		memory/EntityControl.cpp \
		memory/LeavePeriod.cpp \
		memory/Raise.cpp \
		memory/TermRole.cpp \
		memory/User.cpp \
		integration/Transaction.cpp \
		integration/TransactionFileCreator.cpp \
		integration/AttributePair.cpp \
		integration/TransactionFileHandler.cpp \
		integration/AddEmployeeTransaction.cpp \
		integration/UpdateBasicTransaction.cpp \
		integration/UpdatePayTransaction.cpp \
		integration/ApplyRaiseTransaction.cpp \
		integration/AddLeaveTransaction.cpp \
		memory/EntityManager.cpp \
		database/StorageManager.cpp \
		integration/TransactionIntegrator.cpp \
		database/StorageConnection.cpp \
		integration/AddRoleTransaction.cpp \
		gui/mainwindow.cpp \
		gui/secondwindow.cpp \
		gui/thirdwindow.cpp \
		gui/fourthwindow.cpp \
		gui/dataintegration.cpp \
		ApplicationLogic.cpp \
		memory/PayrollSummary.cpp
QMAKE_TARGET  = cuNICS
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = cuNICS


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h ui_secondwindow.h ui_thirdwindow.h ui_fourthwindow.h ui_dataintegration.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cuNICS.pro /usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf \
		cuNICS.pro \
		/usr/lib/i386-linux-gnu/libQt5Widgets.prl \
		/usr/lib/i386-linux-gnu/libQt5Gui.prl \
		/usr/lib/i386-linux-gnu/libQt5Sql.prl \
		/usr/lib/i386-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile cuNICS.pro
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf:
cuNICS.pro:
/usr/lib/i386-linux-gnu/libQt5Widgets.prl:
/usr/lib/i386-linux-gnu/libQt5Gui.prl:
/usr/lib/i386-linux-gnu/libQt5Sql.prl:
/usr/lib/i386-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile cuNICS.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents database/DatabaseControl.h memory/Address.h memory/ContinuingRole.h memory/Date.h memory/Deduction.h memory/Employee.h memory/EmployeeRole.h memory/EntityControl.h memory/LeavePeriod.h memory/Raise.h memory/TermRole.h memory/User.h integration/Transaction.h integration/TransactionFileCreator.h integration/AttributePair.h integration/IntegrationUtils.h integration/TransactionFileHandler.h integration/AddEmployeeTransaction.h integration/UpdateBasicTransaction.h integration/UpdatePayTransaction.h integration/ApplyRaiseTransaction.h integration/AddLeaveTransaction.h memory/EntityManager.h database/StorageManager.h integration/TransactionIntegrator.h database/StorageConnection.h integration/AddRoleTransaction.h gui/mainwindow.h gui/secondwindow.h gui/thirdwindow.h gui/fourthwindow.h gui/dataintegration.h ApplicationLogic.h memory/PayrollSummary.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp database/DatabaseControl.cpp memory/Address.cpp memory/ContinuingRole.cpp memory/Date.cpp memory/Deduction.cpp memory/Employee.cpp memory/EmployeeRole.cpp memory/EntityControl.cpp memory/LeavePeriod.cpp memory/Raise.cpp memory/TermRole.cpp memory/User.cpp integration/Transaction.cpp integration/TransactionFileCreator.cpp integration/AttributePair.cpp integration/TransactionFileHandler.cpp integration/AddEmployeeTransaction.cpp integration/UpdateBasicTransaction.cpp integration/UpdatePayTransaction.cpp integration/ApplyRaiseTransaction.cpp integration/AddLeaveTransaction.cpp memory/EntityManager.cpp database/StorageManager.cpp integration/TransactionIntegrator.cpp database/StorageConnection.cpp integration/AddRoleTransaction.cpp gui/mainwindow.cpp gui/secondwindow.cpp gui/thirdwindow.cpp gui/fourthwindow.cpp gui/dataintegration.cpp ApplicationLogic.cpp memory/PayrollSummary.cpp $(DISTDIR)/
	$(COPY_FILE) --parents gui/mainwindow.ui gui/secondwindow.ui gui/thirdwindow.ui gui/fourthwindow.ui gui/dataintegration.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_secondwindow.cpp moc_thirdwindow.cpp moc_fourthwindow.cpp moc_dataintegration.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_secondwindow.cpp moc_thirdwindow.cpp moc_fourthwindow.cpp moc_dataintegration.cpp
moc_mainwindow.cpp: gui/secondwindow.h \
		gui/thirdwindow.h \
		ApplicationLogic.h \
		memory/EntityManager.h \
		memory/Deduction.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		database/StorageManager.h \
		integration/AttributePair.h \
		integration/IntegrationUtils.h \
		database/StorageConnection.h \
		integration/TransactionFileCreator.h \
		integration/TransactionIntegrator.h \
		integration/TransactionFileHandler.h \
		gui/fourthwindow.h \
		gui/dataintegration.h \
		gui/mainwindow.h
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/admin/Documents/COMP-3004-Project -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtSql -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/i386-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/i686-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/5/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include gui/mainwindow.h -o moc_mainwindow.cpp

moc_secondwindow.cpp: gui/thirdwindow.h \
		ApplicationLogic.h \
		memory/EntityManager.h \
		memory/Deduction.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		database/StorageManager.h \
		integration/AttributePair.h \
		integration/IntegrationUtils.h \
		database/StorageConnection.h \
		integration/TransactionFileCreator.h \
		integration/TransactionIntegrator.h \
		integration/TransactionFileHandler.h \
		gui/fourthwindow.h \
		gui/dataintegration.h \
		gui/secondwindow.h
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/admin/Documents/COMP-3004-Project -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtSql -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/i386-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/i686-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/5/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include gui/secondwindow.h -o moc_secondwindow.cpp

moc_thirdwindow.cpp: ApplicationLogic.h \
		memory/EntityManager.h \
		memory/Deduction.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		database/StorageManager.h \
		integration/AttributePair.h \
		integration/IntegrationUtils.h \
		database/StorageConnection.h \
		integration/TransactionFileCreator.h \
		integration/TransactionIntegrator.h \
		integration/TransactionFileHandler.h \
		gui/thirdwindow.h
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/admin/Documents/COMP-3004-Project -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtSql -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/i386-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/i686-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/5/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include gui/thirdwindow.h -o moc_thirdwindow.cpp

moc_fourthwindow.cpp: gui/fourthwindow.h
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/admin/Documents/COMP-3004-Project -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtSql -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/i386-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/i686-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/5/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include gui/fourthwindow.h -o moc_fourthwindow.cpp

moc_dataintegration.cpp: ApplicationLogic.h \
		memory/EntityManager.h \
		memory/Deduction.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		database/StorageManager.h \
		integration/AttributePair.h \
		integration/IntegrationUtils.h \
		database/StorageConnection.h \
		integration/TransactionFileCreator.h \
		integration/TransactionIntegrator.h \
		integration/TransactionFileHandler.h \
		gui/dataintegration.h
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/admin/Documents/COMP-3004-Project -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtSql -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/i386-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/i686-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/5/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include gui/dataintegration.h -o moc_dataintegration.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_secondwindow.h ui_thirdwindow.h ui_fourthwindow.h ui_dataintegration.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_secondwindow.h ui_thirdwindow.h ui_fourthwindow.h ui_dataintegration.h
ui_mainwindow.h: gui/mainwindow.ui
	/usr/lib/i386-linux-gnu/qt5/bin/uic gui/mainwindow.ui -o ui_mainwindow.h

ui_secondwindow.h: gui/secondwindow.ui
	/usr/lib/i386-linux-gnu/qt5/bin/uic gui/secondwindow.ui -o ui_secondwindow.h

ui_thirdwindow.h: gui/thirdwindow.ui
	/usr/lib/i386-linux-gnu/qt5/bin/uic gui/thirdwindow.ui -o ui_thirdwindow.h

ui_fourthwindow.h: gui/fourthwindow.ui
	/usr/lib/i386-linux-gnu/qt5/bin/uic gui/fourthwindow.ui -o ui_fourthwindow.h

ui_dataintegration.h: gui/dataintegration.ui
	/usr/lib/i386-linux-gnu/qt5/bin/uic gui/dataintegration.ui -o ui_dataintegration.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp gui/mainwindow.h \
		gui/secondwindow.h \
		gui/thirdwindow.h \
		ApplicationLogic.h \
		memory/EntityManager.h \
		memory/Deduction.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		database/StorageManager.h \
		integration/AttributePair.h \
		integration/IntegrationUtils.h \
		database/StorageConnection.h \
		integration/TransactionFileCreator.h \
		integration/TransactionIntegrator.h \
		integration/TransactionFileHandler.h \
		gui/fourthwindow.h \
		gui/dataintegration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

DatabaseControl.o: database/DatabaseControl.cpp database/DatabaseControl.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/TermRole.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		memory/Deduction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DatabaseControl.o database/DatabaseControl.cpp

Address.o: memory/Address.cpp memory/Address.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Address.o memory/Address.cpp

ContinuingRole.o: memory/ContinuingRole.cpp memory/ContinuingRole.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/LeavePeriod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ContinuingRole.o memory/ContinuingRole.cpp

Date.o: memory/Date.cpp memory/Date.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Date.o memory/Date.cpp

Deduction.o: memory/Deduction.cpp memory/Deduction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Deduction.o memory/Deduction.cpp

Employee.o: memory/Employee.cpp memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Employee.o memory/Employee.cpp

EmployeeRole.o: memory/EmployeeRole.cpp memory/EmployeeRole.h \
		memory/Date.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/TermRole.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EmployeeRole.o memory/EmployeeRole.cpp

EntityControl.o: memory/EntityControl.cpp memory/EntityControl.h \
		database/DatabaseControl.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/TermRole.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		memory/Deduction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EntityControl.o memory/EntityControl.cpp

LeavePeriod.o: memory/LeavePeriod.cpp memory/LeavePeriod.h \
		memory/Date.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LeavePeriod.o memory/LeavePeriod.cpp

Raise.o: memory/Raise.cpp memory/Raise.h \
		memory/Date.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Raise.o memory/Raise.cpp

TermRole.o: memory/TermRole.cpp memory/TermRole.h \
		memory/EmployeeRole.h \
		memory/Date.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TermRole.o memory/TermRole.cpp

User.o: memory/User.cpp memory/User.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o User.o memory/User.cpp

Transaction.o: integration/Transaction.cpp integration/Transaction.h \
		memory/EntityManager.h \
		memory/Deduction.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		database/StorageManager.h \
		integration/AttributePair.h \
		integration/IntegrationUtils.h \
		database/StorageConnection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Transaction.o integration/Transaction.cpp

TransactionFileCreator.o: integration/TransactionFileCreator.cpp integration/TransactionFileCreator.h \
		integration/AttributePair.h \
		integration/IntegrationUtils.h \
		memory/Date.h \
		memory/EmployeeRole.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TransactionFileCreator.o integration/TransactionFileCreator.cpp

AttributePair.o: integration/AttributePair.cpp integration/AttributePair.h \
		integration/IntegrationUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AttributePair.o integration/AttributePair.cpp

TransactionFileHandler.o: integration/TransactionFileHandler.cpp integration/TransactionFileHandler.h \
		integration/IntegrationUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TransactionFileHandler.o integration/TransactionFileHandler.cpp

AddEmployeeTransaction.o: integration/AddEmployeeTransaction.cpp integration/AddEmployeeTransaction.h \
		integration/Transaction.h \
		memory/EntityManager.h \
		memory/Deduction.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		database/StorageManager.h \
		integration/AttributePair.h \
		integration/IntegrationUtils.h \
		database/StorageConnection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AddEmployeeTransaction.o integration/AddEmployeeTransaction.cpp

UpdateBasicTransaction.o: integration/UpdateBasicTransaction.cpp integration/UpdateBasicTransaction.h \
		integration/Transaction.h \
		memory/EntityManager.h \
		memory/Deduction.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		database/StorageManager.h \
		integration/AttributePair.h \
		integration/IntegrationUtils.h \
		database/StorageConnection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UpdateBasicTransaction.o integration/UpdateBasicTransaction.cpp

UpdatePayTransaction.o: integration/UpdatePayTransaction.cpp integration/UpdatePayTransaction.h \
		integration/Transaction.h \
		memory/EntityManager.h \
		memory/Deduction.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		database/StorageManager.h \
		integration/AttributePair.h \
		integration/IntegrationUtils.h \
		database/StorageConnection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UpdatePayTransaction.o integration/UpdatePayTransaction.cpp

ApplyRaiseTransaction.o: integration/ApplyRaiseTransaction.cpp integration/ApplyRaiseTransaction.h \
		integration/Transaction.h \
		memory/EntityManager.h \
		memory/Deduction.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		database/StorageManager.h \
		integration/AttributePair.h \
		integration/IntegrationUtils.h \
		database/StorageConnection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ApplyRaiseTransaction.o integration/ApplyRaiseTransaction.cpp

AddLeaveTransaction.o: integration/AddLeaveTransaction.cpp integration/AddLeaveTransaction.h \
		integration/Transaction.h \
		memory/EntityManager.h \
		memory/Deduction.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		database/StorageManager.h \
		integration/AttributePair.h \
		integration/IntegrationUtils.h \
		database/StorageConnection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AddLeaveTransaction.o integration/AddLeaveTransaction.cpp

EntityManager.o: memory/EntityManager.cpp memory/EntityManager.h \
		memory/Deduction.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		database/StorageManager.h \
		integration/AttributePair.h \
		integration/IntegrationUtils.h \
		database/StorageConnection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EntityManager.o memory/EntityManager.cpp

StorageManager.o: database/StorageManager.cpp database/StorageManager.h \
		memory/Deduction.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		integration/AttributePair.h \
		integration/IntegrationUtils.h \
		database/StorageConnection.h \
		memory/TermRole.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StorageManager.o database/StorageManager.cpp

TransactionIntegrator.o: integration/TransactionIntegrator.cpp integration/TransactionIntegrator.h \
		integration/IntegrationUtils.h \
		integration/TransactionFileHandler.h \
		memory/EntityManager.h \
		memory/Deduction.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		database/StorageManager.h \
		integration/AttributePair.h \
		database/StorageConnection.h \
		integration/Transaction.h \
		integration/AddEmployeeTransaction.h \
		integration/AddLeaveTransaction.h \
		integration/AddRoleTransaction.h \
		integration/ApplyRaiseTransaction.h \
		integration/UpdateBasicTransaction.h \
		integration/UpdatePayTransaction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TransactionIntegrator.o integration/TransactionIntegrator.cpp

StorageConnection.o: database/StorageConnection.cpp database/StorageConnection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StorageConnection.o database/StorageConnection.cpp

AddRoleTransaction.o: integration/AddRoleTransaction.cpp integration/AddRoleTransaction.h \
		integration/Transaction.h \
		memory/EntityManager.h \
		memory/Deduction.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		database/StorageManager.h \
		integration/AttributePair.h \
		integration/IntegrationUtils.h \
		database/StorageConnection.h \
		memory/TermRole.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AddRoleTransaction.o integration/AddRoleTransaction.cpp

mainwindow.o: gui/mainwindow.cpp gui/mainwindow.h \
		gui/secondwindow.h \
		gui/thirdwindow.h \
		ApplicationLogic.h \
		memory/EntityManager.h \
		memory/Deduction.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		database/StorageManager.h \
		integration/AttributePair.h \
		integration/IntegrationUtils.h \
		database/StorageConnection.h \
		integration/TransactionFileCreator.h \
		integration/TransactionIntegrator.h \
		integration/TransactionFileHandler.h \
		gui/fourthwindow.h \
		gui/dataintegration.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o gui/mainwindow.cpp

secondwindow.o: gui/secondwindow.cpp gui/secondwindow.h \
		gui/thirdwindow.h \
		ApplicationLogic.h \
		memory/EntityManager.h \
		memory/Deduction.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		database/StorageManager.h \
		integration/AttributePair.h \
		integration/IntegrationUtils.h \
		database/StorageConnection.h \
		integration/TransactionFileCreator.h \
		integration/TransactionIntegrator.h \
		integration/TransactionFileHandler.h \
		gui/fourthwindow.h \
		gui/dataintegration.h \
		ui_secondwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o secondwindow.o gui/secondwindow.cpp

thirdwindow.o: gui/thirdwindow.cpp gui/thirdwindow.h \
		ApplicationLogic.h \
		memory/EntityManager.h \
		memory/Deduction.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		database/StorageManager.h \
		integration/AttributePair.h \
		integration/IntegrationUtils.h \
		database/StorageConnection.h \
		integration/TransactionFileCreator.h \
		integration/TransactionIntegrator.h \
		integration/TransactionFileHandler.h \
		gui/secondwindow.h \
		gui/fourthwindow.h \
		gui/dataintegration.h \
		ui_thirdwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o thirdwindow.o gui/thirdwindow.cpp

fourthwindow.o: gui/fourthwindow.cpp gui/fourthwindow.h \
		ui_fourthwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fourthwindow.o gui/fourthwindow.cpp

dataintegration.o: gui/dataintegration.cpp gui/dataintegration.h \
		ApplicationLogic.h \
		memory/EntityManager.h \
		memory/Deduction.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		database/StorageManager.h \
		integration/AttributePair.h \
		integration/IntegrationUtils.h \
		database/StorageConnection.h \
		integration/TransactionFileCreator.h \
		integration/TransactionIntegrator.h \
		integration/TransactionFileHandler.h \
		ui_dataintegration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dataintegration.o gui/dataintegration.cpp

ApplicationLogic.o: ApplicationLogic.cpp ApplicationLogic.h \
		memory/EntityManager.h \
		memory/Deduction.h \
		memory/Employee.h \
		memory/User.h \
		memory/Address.h \
		memory/EmployeeRole.h \
		memory/Date.h \
		memory/ContinuingRole.h \
		memory/LeavePeriod.h \
		memory/Raise.h \
		database/StorageManager.h \
		integration/AttributePair.h \
		integration/IntegrationUtils.h \
		database/StorageConnection.h \
		integration/TransactionFileCreator.h \
		integration/TransactionIntegrator.h \
		integration/TransactionFileHandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ApplicationLogic.o ApplicationLogic.cpp

PayrollSummary.o: memory/PayrollSummary.cpp memory/PayrollSummary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PayrollSummary.o memory/PayrollSummary.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_secondwindow.o: moc_secondwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_secondwindow.o moc_secondwindow.cpp

moc_thirdwindow.o: moc_thirdwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_thirdwindow.o moc_thirdwindow.cpp

moc_fourthwindow.o: moc_fourthwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fourthwindow.o moc_fourthwindow.cpp

moc_dataintegration.o: moc_dataintegration.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dataintegration.o moc_dataintegration.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

